### ISSUE TITLE
Test vectors

### ISSUE THREAD

**Issue by dhardy** [MartyMacGyver/PractRand#2]
Hello,

To jump straight in: where are the test vectors?

I may be interested in using SFC, however could not do so without a means of verifying the implementation. Even if these are not frozen test-vectors would be useful (obviously requiring versioning).

**Comment by MartyMacGyver** [comment]
As noted in the README, this is just a fork (more of a mirror really) of https://sourceforge.net/projects/pracrand/ . What you have here should be what you'd get from there (which I recommend doing, as what's here is primarily a convenience for myself as SourceForge is a pain).

That said, on that original project they have a bug tracker and a discussion forum that would be the ideal place to ask about this (again, check their code - they actually have a pre-0.95 version out which might have more in it than what I've mirrored here for 0.94).

**Comment by dhardy** [comment]
Ugh, sourceforge being a pain is why I didn't originally comment there. Thanks for the pointer; I started a discussion on the forum there so hopefully the author will get the request.

**Comment by MartyMacGyver** [comment]
Adding the link to the discussion to see how it works out:
https://sourceforge.net/p/pracrand/discussion/366935/thread/65705e7219/
